-- CreateTable
CREATE TABLE "Municipality" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT,
    "population" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Municipality_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PermitDocumentRequirement" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "permitSubtype" TEXT NOT NULL,
    "requiredDocumentTypes" JSONB NOT NULL DEFAULT '[]',
    "updatedBy" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PermitDocumentRequirement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "fullName" TEXT,
    "role" TEXT NOT NULL DEFAULT 'VIEWER',
    "municipalityId" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastLogin" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoadEvent" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "eventType" TEXT NOT NULL,
    "subtype" TEXT NOT NULL,
    "geometry" JSONB NOT NULL,
    "startTime" TIMESTAMP(3) NOT NULL,
    "endTime" TIMESTAMP(3),
    "impacts" JSONB NOT NULL DEFAULT '[]',
    "details" JSONB NOT NULL DEFAULT '{}',
    "sourceType" TEXT NOT NULL DEFAULT 'PERMIT',
    "sourceRef" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "statusReason" TEXT,
    "recurrenceRule" TEXT,
    "contractorEmail" TEXT,
    "contractorToken" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "confidence" DOUBLE PRECISION,
    "createdBy" UUID,
    "submittedBy" UUID,
    "approvedBy" UUID,
    "publishedBy" UUID,
    "closedBy" UUID,
    "submittedAt" TIMESTAMP(3),
    "approvedAt" TIMESTAMP(3),
    "publishedAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RoadEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Inspection" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "permitId" UUID,
    "assignedTo" UUID,
    "assignedAt" TIMESTAMP(3),
    "assignedBy" UUID,
    "scheduledAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),
    "address" TEXT NOT NULL,
    "inspectionType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "outcome" TEXT,
    "notes" TEXT,
    "findings" TEXT,
    "createdBy" UUID NOT NULL,
    "completedBy" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Inspection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InspectionEvidence" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "inspectionId" UUID NOT NULL,
    "evidenceType" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "storageKey" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "description" TEXT,
    "capturedAt" TIMESTAMP(3) NOT NULL,
    "uploadedBy" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "InspectionEvidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InspectionReminder" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "inspectionId" UUID NOT NULL,
    "recipientId" UUID NOT NULL,
    "reminderType" TEXT NOT NULL,
    "scheduledFor" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "acknowledgedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InspectionReminder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CitizenRequest" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "citizenId" UUID NOT NULL,
    "assignedTo" UUID,
    "assignedTeam" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'OTHER',
    "status" TEXT NOT NULL DEFAULT 'SUBMITTED',
    "location" JSONB,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "resolution" TEXT,
    "assignedAt" TIMESTAMP(3),
    "resolvedAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CitizenRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CitizenRequestEvent" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "requestId" UUID NOT NULL,
    "actorId" UUID,
    "eventType" TEXT NOT NULL,
    "fromStatus" TEXT,
    "toStatus" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CitizenRequestEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CitizenMessage" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "requestId" UUID NOT NULL,
    "authorId" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "visibility" TEXT NOT NULL DEFAULT 'CITIZEN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CitizenMessage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Notification" (
    "id" UUID NOT NULL,
    "municipalityId" INTEGER NOT NULL,
    "recipientId" UUID NOT NULL,
    "requestId" UUID,
    "eventType" TEXT NOT NULL,
    "channel" TEXT NOT NULL DEFAULT 'IN_APP',
    "subject" TEXT,
    "body" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "nextAttemptAt" TIMESTAMP(3),
    "deliveredAt" TIMESTAMP(3),
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Municipality_name_key" ON "Municipality"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Municipality_code_key" ON "Municipality"("code");

-- CreateIndex
CREATE INDEX "PermitDocumentRequirement_municipalityId_updatedAt_idx" ON "PermitDocumentRequirement"("municipalityId", "updatedAt");

-- CreateIndex
CREATE UNIQUE INDEX "PermitDocumentRequirement_municipalityId_permitSubtype_key" ON "PermitDocumentRequirement"("municipalityId", "permitSubtype");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "RoadEvent_contractorToken_key" ON "RoadEvent"("contractorToken");

-- CreateIndex
CREATE INDEX "RoadEvent_municipalityId_status_idx" ON "RoadEvent"("municipalityId", "status");

-- CreateIndex
CREATE INDEX "RoadEvent_startTime_endTime_idx" ON "RoadEvent"("startTime", "endTime");

-- CreateIndex
CREATE INDEX "Inspection_municipalityId_status_idx" ON "Inspection"("municipalityId", "status");

-- CreateIndex
CREATE INDEX "Inspection_municipalityId_scheduledAt_idx" ON "Inspection"("municipalityId", "scheduledAt");

-- CreateIndex
CREATE INDEX "Inspection_municipalityId_assignedTo_idx" ON "Inspection"("municipalityId", "assignedTo");

-- CreateIndex
CREATE INDEX "Inspection_permitId_idx" ON "Inspection"("permitId");

-- CreateIndex
CREATE INDEX "InspectionEvidence_municipalityId_inspectionId_idx" ON "InspectionEvidence"("municipalityId", "inspectionId");

-- CreateIndex
CREATE INDEX "InspectionEvidence_inspectionId_capturedAt_idx" ON "InspectionEvidence"("inspectionId", "capturedAt");

-- CreateIndex
CREATE INDEX "InspectionEvidence_sha256_idx" ON "InspectionEvidence"("sha256");

-- CreateIndex
CREATE UNIQUE INDEX "InspectionEvidence_municipalityId_storageKey_key" ON "InspectionEvidence"("municipalityId", "storageKey");

-- CreateIndex
CREATE INDEX "InspectionReminder_municipalityId_recipientId_status_idx" ON "InspectionReminder"("municipalityId", "recipientId", "status");

-- CreateIndex
CREATE INDEX "InspectionReminder_scheduledFor_status_idx" ON "InspectionReminder"("scheduledFor", "status");

-- CreateIndex
CREATE UNIQUE INDEX "InspectionReminder_inspectionId_recipientId_reminderType_sc_key" ON "InspectionReminder"("inspectionId", "recipientId", "reminderType", "scheduledFor");

-- CreateIndex
CREATE INDEX "CitizenRequest_municipalityId_status_updatedAt_idx" ON "CitizenRequest"("municipalityId", "status", "updatedAt");

-- CreateIndex
CREATE INDEX "CitizenRequest_municipalityId_citizenId_updatedAt_idx" ON "CitizenRequest"("municipalityId", "citizenId", "updatedAt");

-- CreateIndex
CREATE INDEX "CitizenRequest_municipalityId_assignedTo_status_idx" ON "CitizenRequest"("municipalityId", "assignedTo", "status");

-- CreateIndex
CREATE INDEX "CitizenRequest_category_status_idx" ON "CitizenRequest"("category", "status");

-- CreateIndex
CREATE INDEX "CitizenRequestEvent_municipalityId_requestId_createdAt_idx" ON "CitizenRequestEvent"("municipalityId", "requestId", "createdAt");

-- CreateIndex
CREATE INDEX "CitizenRequestEvent_actorId_createdAt_idx" ON "CitizenRequestEvent"("actorId", "createdAt");

-- CreateIndex
CREATE INDEX "CitizenMessage_municipalityId_requestId_createdAt_idx" ON "CitizenMessage"("municipalityId", "requestId", "createdAt");

-- CreateIndex
CREATE INDEX "CitizenMessage_authorId_createdAt_idx" ON "CitizenMessage"("authorId", "createdAt");

-- CreateIndex
CREATE INDEX "Notification_municipalityId_recipientId_status_createdAt_idx" ON "Notification"("municipalityId", "recipientId", "status", "createdAt");

-- CreateIndex
CREATE INDEX "Notification_municipalityId_eventType_createdAt_idx" ON "Notification"("municipalityId", "eventType", "createdAt");

-- CreateIndex
CREATE INDEX "Notification_nextAttemptAt_status_idx" ON "Notification"("nextAttemptAt", "status");

-- AddForeignKey
ALTER TABLE "PermitDocumentRequirement" ADD CONSTRAINT "PermitDocumentRequirement_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadEvent" ADD CONSTRAINT "RoadEvent_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Inspection" ADD CONSTRAINT "Inspection_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Inspection" ADD CONSTRAINT "Inspection_assignedTo_fkey" FOREIGN KEY ("assignedTo") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InspectionEvidence" ADD CONSTRAINT "InspectionEvidence_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InspectionEvidence" ADD CONSTRAINT "InspectionEvidence_inspectionId_fkey" FOREIGN KEY ("inspectionId") REFERENCES "Inspection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InspectionReminder" ADD CONSTRAINT "InspectionReminder_inspectionId_fkey" FOREIGN KEY ("inspectionId") REFERENCES "Inspection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenRequest" ADD CONSTRAINT "CitizenRequest_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenRequest" ADD CONSTRAINT "CitizenRequest_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenRequest" ADD CONSTRAINT "CitizenRequest_assignedTo_fkey" FOREIGN KEY ("assignedTo") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenRequestEvent" ADD CONSTRAINT "CitizenRequestEvent_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenRequestEvent" ADD CONSTRAINT "CitizenRequestEvent_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "CitizenRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenRequestEvent" ADD CONSTRAINT "CitizenRequestEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenMessage" ADD CONSTRAINT "CitizenMessage_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenMessage" ADD CONSTRAINT "CitizenMessage_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "CitizenRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CitizenMessage" ADD CONSTRAINT "CitizenMessage_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_municipalityId_fkey" FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "CitizenRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
