export interface User {
  id: string;
  email: string;
  fullName?: string;
  role: 'ADMIN' | 'MUNICIPAL_AGENT' | 'CONTRACTOR' | 'VIEWER';
  municipalityId?: number;
}

export interface RoadEvent {
  id: string;
  municipalityId: number;
  eventType: 'CONSTRUCTION' | 'REGULATION' | 'EVENT' | 'INCIDENT' | 'RESTRICTION';
  subtype: string;
  geometry: GeoJSON.Geometry;
  startTime: string;
  endTime?: string;
  impacts: string[];
  details: Record<string, unknown>;
  sourceType: string;
  sourceRef?: string;
  status: 'DRAFT' | 'PLANNED' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED' | 'TEMP';
  autoGenerated?: boolean;
  confidence?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Municipality {
  id: number;
  name: string;
  code?: string;
  population?: number;
}
