export type UserRole =
  | "ADMIN"
  | "MANAGER"
  | "MUNICIPAL_AGENT"
  | "INSPECTOR"
  | "CONTRACTOR"
  | "VIEWER"
  | "CITIZEN";

export interface User {
  id: string;
  email: string;
  fullName?: string;
  role: UserRole;
  municipalityId?: number;
}

export interface RoadEvent {
  id: string;
  municipalityId: number;
  eventType:
    | "CONSTRUCTION"
    | "REGULATION"
    | "EVENT"
    | "INCIDENT"
    | "RESTRICTION";
  subtype: string;
  geometry: GeoJSON.Geometry;
  startTime: string;
  endTime?: string;
  impacts: string[];
  details: Record<string, unknown>;
  sourceType: string;
  sourceRef?: string;
  status:
    | "DRAFT"
    | "PLANNED"
    | "ACTIVE"
    | "COMPLETED"
    | "CANCELLED"
    | "TEMP";
  autoGenerated?: boolean;
  confidence?: number;
  createdAt: string;
  updatedAt: string;
}

export type InspectionType =
  | "PRE_WORK"
  | "IN_PROGRESS"
  | "FINAL"
  | "COMPLAINT";
export type InspectionStatus = "SCHEDULED" | "COMPLETED" | "CANCELLED";
export type InspectionOutcome =
  | "COMPLIANT"
  | "NON_COMPLIANT"
  | "FOLLOW_UP_REQUIRED";

export interface Inspection {
  id: string;
  municipalityId: number;
  permitId?: string | null;
  scheduledAt: string;
  address: string;
  inspectionType: InspectionType;
  notes?: string | null;
  status: InspectionStatus;
  outcome?: InspectionOutcome | null;
  findings?: string | null;
  completedAt?: string | null;
  createdBy: string;
  completedBy?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateInspectionInput {
  permitId?: string | null;
  scheduledAt: string;
  address: string;
  inspectionType: InspectionType;
  notes?: string | null;
}

export interface CompleteInspectionInput {
  outcome: InspectionOutcome;
  findings: string;
  completedAt?: string;
}

export interface Municipality {
  id: number;
  name: string;
  code?: string;
  population?: number;
}
