const express = require('express');
require('express-async-errors');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const compression = require('compression');
const errorHandler = require('./api/middleware/errorHandler');

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173' }));
app.use(compression());
app.use(morgan('dev'));
app.use(express.json({ limit: '10mb' }));
app.use('/api/v1/auth', require('./api/routes/auth'));
app.use('/api/v1/events', require('./api/routes/events'));
app.use('/api/v1/exports', require('./api/routes/exports'));
app.use('/api/v1/permits', require('./api/routes/permits'));
app.use('/api/v1/work-orders', require('./api/routes/workOrders'));
app.use('/api/v1/operations', require('./api/routes/operations'));
app.use('/api/v1/inspection-reminders', require('./api/routes/inspectionReminders'));
app.use('/api/v1/inspection-calendar', require('./api/routes/inspectionCalendar'));
app.use('/api/v1/inspection-dashboard', require('./api/routes/inspectionDashboard'));
app.use('/api/v1/inspection-trends', require('./api/routes/inspectionTrends'));
app.use('/api/v1/inspections/:inspectionId/evidence', require('./api/routes/inspectionEvidence'));
app.use('/api/v1/inspections', require('./api/routes/inspections'));
app.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.use(errorHandler);
module.exports = app;
