const INSPECTION_TYPES = Object.freeze(['PRE_WORK', 'IN_PROGRESS', 'FINAL', 'COMPLAINT']);
const INSPECTION_STATUSES = Object.freeze(['SCHEDULED', 'COMPLETED', 'CANCELLED']);
const INSPECTION_OUTCOMES = Object.freeze(['COMPLIANT', 'NON_COMPLIANT', 'FOLLOW_UP_REQUIRED']);

module.exports = {
  INSPECTION_TYPES,
  INSPECTION_STATUSES,
  INSPECTION_OUTCOMES
};
