CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "Municipality" (
  "id" SERIAL NOT NULL,
  "name" TEXT NOT NULL,
  "code" TEXT,
  "population" INTEGER,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Municipality_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "User" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "fullName" TEXT,
  "role" TEXT NOT NULL DEFAULT 'VIEWER',
  "municipalityId" INTEGER,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "lastLogin" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RoadEvent" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "municipalityId" INTEGER NOT NULL,
  "eventType" TEXT NOT NULL,
  "subtype" TEXT NOT NULL,
  "geometry" JSONB NOT NULL,
  "startTime" TIMESTAMP(3) NOT NULL,
  "endTime" TIMESTAMP(3),
  "impacts" JSONB NOT NULL DEFAULT '[]',
  "details" JSONB NOT NULL DEFAULT '{}',
  "sourceType" TEXT NOT NULL DEFAULT 'PERMIT',
  "sourceRef" TEXT,
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "recurrenceRule" TEXT,
  "contractorEmail" TEXT,
  "contractorToken" TEXT,
  "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
  "confidence" DOUBLE PRECISION,
  "createdBy" UUID,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "RoadEvent_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Municipality_name_key" ON "Municipality"("name");
CREATE UNIQUE INDEX "Municipality_code_key" ON "Municipality"("code");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "RoadEvent_contractorToken_key" ON "RoadEvent"("contractorToken");

CREATE INDEX "RoadEvent_municipalityId_status_idx" ON "RoadEvent"("municipalityId", "status");
CREATE INDEX "RoadEvent_startTime_endTime_idx" ON "RoadEvent"("startTime", "endTime");

ALTER TABLE "User"
  ADD CONSTRAINT "User_municipalityId_fkey"
  FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "RoadEvent"
  ADD CONSTRAINT "RoadEvent_municipalityId_fkey"
  FOREIGN KEY ("municipalityId") REFERENCES "Municipality"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
